---
name: influxdb
volume: influxdb_volume
conf_file: influxdb.conf
conf_dir: /etc/influxdb
conf_path: "{{conf_dir}}/{{conf_file}}"
service_definition: >
  --name {{ name }}
  --network appnet
  -p 8083:8083/tcp
  -p 8086:8086/tcp
  --mount type=volume,src={{volume}},dst={{conf_dir}}
  influxdb -config {{conf_path}}
