---
- name: Install epel
  yum: name=epel-release state=latest

- name: Install required packages
  yum: name={{ item }} state=latest
  with_items:
    - nc
    - nmap
    - htop
    - sysstat
    - python-pip
    - bind-utils
    - jq # Json formatting
  tags:
    - packages

- name: install docker python dependencies
  pip: name={{ item.name }} version={{ item.version | default(omit) }}
  with_items:
    - { name: pyyaml }
    - { name: docker-py, version: 1.9.0 }
  tags:
    - packages